spring.application.name=metaextract
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
server.port=8081  

# API Keys — loaded from environment variables (never hardcode here)
groq.api.key=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
opencage.api.key=312be13fa1b24a149fa1318378e54095
ors.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjZkMTk5MzEwY2YyNDQxMGY5NDljMDI4M2UwZWQ4ZjkyIiwiaCI6Im11cm11cjY0In0=